path_to_root_dir = r'/home/sam/dev/fyp/lexis_nexis_scraping/'
output_folder = path_to_root_dir + r'download_monthly'
download_folder = path_to_root_dir + r'download'
data_folder = path_to_root_dir + r'data/'
tmp_folder = path_to_root_dir + r'tmp'

articles_words_freq = 'articles_body_frequencies.json'
titles_words_freq = 'title_frequencies.json'
title_monthly_frequencies = 'title_monthly_frequencies.json'
articles_monthly_frequencies = 'articles_monthly_frequencies.json'
title_weekly_frequencies = 'title_weekly_frequencies.json'
articles_weekly_frequencies = 'articles_weekly_frequencies.json'
weekly_average_word_count = 'weekly_average_word_count.json'
monthly_average_word_count = 'monthly_average_word_count.json'

loaded_batches_full_path = r'data/db/loaded_batches.txt'
current_batch_full_path = r'data/db/current_batch.txt'
titles_word_freq_wordcloud = r'data/plots/titles_word_freq_wordcloud.png'
articles_word_freq_wordcloud = r'data/plots/articles_word_freq_wordcloud.png'
FEEL_lexicon = r'FEEL/FEEL.csv'
