#!/bin/sh

# Set these paths appropriately

BIN="/home/sam/dev/fyp/treetagger/bin"
CMD="/home/sam/dev/fyp/treetagger/cmd"
LIB="/home/sam/dev/fyp/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
