#!/bin/sh

# Set these paths appropriately

BIN="/home/sam/dev/fyp/treetagger/bin"
CMD="/home/sam/dev/fyp/treetagger/cmd"
LIB="/home/sam/dev/fyp/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
